### ISSUE TITLE
Cấu hình huấn luyện

### ISSUE THREAD

**Issue by huytuong010101** [phkhanhtrinh23/question_answering_bartpho#2]
Hi @phkhanhtrinh23 ,
Mình thấy repo của bạn khá hay. Mình đang huấn luyện lại mô hình theo hướng dẫn của bạn.
Mình thấy cần GPU memory khá cao.
Không biết để huấn luyện mô hình này thì bạn đang set batch size bao nhiêu và thông số GPU của bạn như thế nào nhỉ.
Mình xin cảm ơn.

**Comment by phkhanhtrinh23** [comment]
Cảm ơn bạn đã quan tâm. Theo mình nhớ, thời điểm huấn luyện mô hình mình để batch_size=2 và sử dụng GPU dòng NVIDIA RTX A4000 (16GB).

**Comment by huytuong010101** [comment]
bạn nhớ train hết thời gian bao lâu không ạm, để rmình lựa chọn GPU cho phù hợp

**Comment by phkhanhtrinh23** [comment]
Theo mình nhớ, thời gian huấn luyện kéo dài khoảng 2 đến 3 ngày.

**Comment by huytuong010101** [comment]
okey mình cảm ơn nhiều nhé
